# Fraud case study

## Day 1: building a fraud model

## Day 2: building an app/dashboard

## Tips success

You will quickly run out of time:

*  Use CRISP-DM workflow to analyze data and build a model
*  Iterate quickly, test often, commit often
*  Build deadlines for your work so you stay on track
*  Should have a model by end of day 1
*  Start app once model is working

### CRISP-DM workflow

Follow the [CRISP-DM](https://en.wikipedia.org/wiki/Cross_Industry_Standard_Process_for_Data_Mining) steps:

1.  Business understanding
2.  Data understanding
3.  Data preparation
4.  Modeling
5.  Evaluation
6.  Deployment

# Introduction to case study: data & problem

Let's look at the data.  What format is the data in?  How do you extract it?

In [1]:
ls -lh data

total 556504
-rw-r--r--  1 gmacmillan  staff   239M Aug  2  2016 data.json
-rw-r--r--  1 gmacmillan  staff    33M Feb 15 09:39 data.zip

Unzip the data so you can load it into Python

In [2]:
# !unzip data/data.zip -d data

Initially, work with a subset at first in order to iterate quickly.  But, the file is one giant line of json:

In [3]:
!wc data/data.json

       0 8173151 250481668 data/data.json

Write a quick and dirty script to pull out the first 100 records so we can get code working quickly.

In [4]:
%%writefile subset_json.py
"""head_json.py - extract a couple records from a huge json file.

Syntax: python head_json.py < infile.json > outfile.json
"""

import sys

start_char = '{'
stop_char = '}'
n_records = 1000
level_nesting = 0

while n_records != 0:
    ch = sys.stdin.read(1)
    sys.stdout.write(ch)
    if ch == start_char:
        level_nesting += 1
    if ch == stop_char:
        level_nesting -= 1
        if level_nesting == 0:
            n_records -= 1
sys.stdout.write(']')

Writing subset_json.py

In [8]:
!python data/subset_json.py < data/data.json > data/subset.json

In [9]:
import pandas as pd

df = pd.read_json('data/subset.json')

In [10]:
df.head().T

,0,1,2,3,4
acct_type,fraudster_event,premium,premium,premium,premium
approx_payout_date,1266062400,1296720000,1296172800,1388966400,1297900800
body_length,3852,3499,2601,12347,2417
channels,5,0,8,6,11
country,US,US,US,IE,US
currency,USD,USD,USD,EUR,USD
delivery_method,0,1,1,1,0
description,"<p><a href=""http://s432.photobucket.com/albums...","<p>Join us for a quick, one-night, community-b...","<h3><span class=""subcategory""><strong>Teacher ...","<p style=""margin-bottom: 1.3em; padding-bottom...",<p>Writers and filmmakers need to understand t...
email_domain,gmail.com,ruf.org,pvsd.k12.ca.us,irishtabletennis.com,artsandbusinesscouncil.org
event_created,1262739706,1293832670,1291090956,1360681570,1291994666
event_end,1265630400,1296288000,1295740800,1388534400,1297468800
event_published,1.26311e+09,1.29383e+09,1.29109e+09,1.36068e+09,1.29199e+09
event_start,1265594400,1296255600,1295713800,1360702800,1297440000
fb_published,0,0,0,0,1
gts,0,868.02,3500,1167.35,2313.15
has_analytics,0,0,0,0,0
has_header,1,0,NaN,0,0
has_logo,0,1,0,1,0
listed,y,n,y,y,y
name,"99 HOUR ""NO SLEEP"" SUPER BOWL CELEBRITY WEEKEN...",Winthrop RUF Winter Getaway,DRDP (2010) Teacher Training,ITTA Affiliation 2013,Self Defense for Writers and Filmmakers: For A...
name_length,60,27,28,21,66
num_order,0,23,19,39,30
num_payouts,0,1,4,16,0
object_id,527017,786878,787337,885645,1114349
org_desc,,"<p>Since 1987, RUF has ministered to students ...","<p><a href=""http://www.desiredresults.com"">www...",,"<p><font face=""Arial""><font size=""2""><strong>T..."
org_facebook,0,0,0,0,0
org_name,Party Starz Ent & Diverse Int'l Group,RUF at Winthrop University,University Preparation School in collaboration...,,Arts & Business Council of Greater Boston
org_twitter,0,12,0,0,0
payee_name,,RUF,University Preparation School,,Arts and Business Council or Greater Boston
payout_type,,CHECK,CHECK,ACH,CHECK
previous_payouts,[],"[{u'name': u'RUF', u'created': u'2010-10-01 01...","[{u'name': u'Danielle Severn', u'created': u'2...","[{u'name': u'', u'created': u'2010-11-09 01:10...",[{u'name': u'Arts and Business Council or Grea...
sale_duration,29,28,54,0,63
sale_duration2,33,28,54,0,63
show_map,1,0,0,0,0
ticket_types,"[{u'event_id': 527017, u'cost': 25.0, u'availa...","[{u'event_id': 786878, u'cost': 35.0, u'availa...","[{u'event_id': 787337, u'cost': 93.51, u'avail...","[{u'event_id': 885645, u'cost': 25.0, u'availa...","[{u'event_id': 1114349, u'cost': 150.0, u'avai..."
user_age,36,149,214,889,35
user_created,1259613950,1280942776,1272559388,1283870102,1288984065
user_type,1,3,3,3,3
venue_address,717 Washington Avenue,,10100 Pioneer Blvd Suite 100,,One Marina Park Drive
venue_country,US,US,US,None,US
venue_latitude,25.7775,32.7766,33.9442,NaN,42.3538
venue_longitude,-80.1334,-79.9309,-118.08,NaN,-71.0443
venue_name,INK Nightclub - South Beach,"The Charleston, SC area",Los Angeles County Office of Education,None,Fish & Richardson
venue_state,FL,SC,CA,None,MA

Some of the data is text (and HTML), which will require feature engineering:

* TF-IDF
* Feature hashing
* n-grams

etc.

You will also need to construct a target from `acct_type`.  Fraud events start with `fraud`.  How you define fraud depends on how you define the business problem.

In [11]:
df.acct_type.value_counts(dropna=False)

premium             845
fraudster_event      65
fraudster            33
spammer_warn         17
spammer_limited      16
tos_warn             10
spammer_noinvite      8
tos_lock              3
locked                2
fraudster_att         1
Name: acct_type, dtype: int64

In [12]:
# list(df.columns)

Is missing data a problem?  What are your options for handling missing data?

In [13]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
approx_payout_date,1000.0,1.351797e+09,2.423362e+07,1.207375e+09,1.336160e+09,1.357457e+09,1.371092e+09,1.419293e+09
body_length,1000.0,3.725574e+03,5.669424e+03,0.000000e+00,7.287500e+02,2.071000e+03,4.367000e+03,6.314300e+04
channels,1000.0,6.219000e+00,3.867039e+00,0.000000e+00,5.000000e+00,6.000000e+00,8.000000e+00,1.300000e+01
delivery_method,998.0,4.498998e-01,6.067119e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.000000e+00
event_created,1000.0,1.346872e+09,2.409548e+07,1.205533e+09,1.331748e+09,1.352394e+09,1.365709e+09,1.381423e+09
event_end,1000.0,1.351365e+09,2.423359e+07,1.206943e+09,1.335728e+09,1.357025e+09,1.370660e+09,1.418861e+09
event_published,990.0,1.344520e+09,6.482996e+07,0.000000e+00,1.331452e+09,1.352383e+09,1.365793e+09,1.381435e+09
event_start,1000.0,1.350972e+09,2.439623e+07,1.206927e+09,1.335317e+09,1.356457e+09,1.370413e+09,1.418850e+09
fb_published,1000.0,1.440000e-01,3.512654e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
gts,1000.0,2.672587e+03,9.735867e+03,0.000000e+00,1.300000e+02,4.545900e+02,1.500053e+03,2.256100e+05
has_analytics,1000.0,7.700000e-02,2.667248e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
has_header,644.0,2.220497e-01,4.159474e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
has_logo,1000.0,8.500000e-01,3.572501e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
name_length,1000.0,4.140500e+01,2.448376e+01,0.000000e+00,2.600000e+01,3.700000e+01,5.200000e+01,2.540000e+02
num_order,1000.0,2.526800e+01,6.921970e+01,0.000000e+00,2.000000e+00,9.000000e+00,2.300000e+01,1.659000e+03
num_payouts,1000.0,3.111100e+01,1.159123e+02,0.000000e+00,0.000000e+00,2.000000e+00,1.400000e+01,1.350000e+03
object_id,1000.0,4.609578e+06,1.973713e+06,1.040110e+05,3.048202e+06,4.685973e+06,6.128988e+06,8.733435e+06
org_facebook,998.0,7.359719e+00,1.132053e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.400000e+01,9.100000e+01
org_twitter,998.0,4.343687e+00,6.132531e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01,2.000000e+01
sale_duration,988.0,4.478745e+01,6.174154e+01,-1.094000e+03,1.600000e+01,3.250000e+01,5.900000e+01,4.500000e+02
sale_duration2,1000.0,4.732500e+01,6.210296e+01,-1.094000e+03,1.700000e+01,3.500000e+01,6.300000e+01,4.490000e+02
show_map,1000.0,8.350000e-01,3.713663e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
user_age,1000.0,3.804140e+02,4.101873e+02,0.000000e+00,1.375000e+01,2.575000e+02,6.180000e+02,2.065000e+03
user_created,1000.0,1.314005e+09,4.075432e+07,1.146260e+09,1.285257e+09,1.317307e+09,1.347112e+09,1.381422e+09
user_type,1000.0,2.713000e+00,1.081573e+00,1.000000e+00,1.000000e+00,3.000000e+00,3.000000e+00,5.000000e+00
venue_latitude,917.0,3.522440e+01,1.974714e+01,-3.786232e+01,3.385097e+01,3.988739e+01,4.445221e+01,6.474396e+01
venue_longitude,917.0,-6.094984e+01,6.553192e+01,-1.580595e+02,-9.758052e+01,-7.973714e+01,-3.181286e+00,1.747752e+02

In [14]:
df['fraud'] = 0
def is_fraud(x):
    if x == 'fraudster' or x == 'fraudster_event':
        return 1
    else:
        return 0

df['fraud'] = df['acct_type'].apply(is_fraud, 1)

def is_listed(x):
    if x == 'y':
        return 1
    else:
        return 0

df['listed'] = df['listed'].apply(is_listed, 1)

In [15]:
df.iloc[:, 15:].head()
# df.user_type.unique()

,has_analytics,has_header,has_logo,listed,name,name_length,num_order,num_payouts,object_id,org_desc,...,user_age,user_created,user_type,venue_address,venue_country,venue_latitude,venue_longitude,venue_name,venue_state,fraud
0,0,1.0,0,1,"99 HOUR ""NO SLEEP"" SUPER BOWL CELEBRITY WEEKEN...",60,0,0,527017,,...,36,1259613950,1,717 Washington Avenue,US,25.777471,-80.133433,INK Nightclub - South Beach,FL,1
1,0,0.0,1,0,Winthrop RUF Winter Getaway,27,23,1,786878,"<p>Since 1987, RUF has ministered to students ...",...,149,1280942776,3,,US,32.776566,-79.930922,"The Charleston, SC area",SC,0
2,0,NaN,0,1,DRDP (2010) Teacher Training,28,19,4,787337,"<p><a href=""http://www.desiredresults.com"">www...",...,214,1272559388,3,10100 Pioneer Blvd Suite 100,US,33.944201,-118.080419,Los Angeles County Office of Education,CA,0
3,0,0.0,1,1,ITTA Affiliation 2013,21,39,16,885645,,...,889,1283870102,3,,None,NaN,NaN,None,None,0
4,0,0.0,0,1,Self Defense for Writers and Filmmakers: For A...,66,30,0,1114349,"<p><font face=""Arial""><font size=""2""><strong>T...",...,35,1288984065,3,One Marina Park Drive,US,42.353848,-71.044276,Fish & Richardson,MA,0

In [16]:
columns_to_del = ['acct_type', 'object_id', 'payee_name', 'ticket_types', 'venue_address', 'venue_latitude', 'venue_longitude', 'venue_state']
dates = ['approx_payout_date', 'event_created', 'event_end', 'event_published', 'event_start', 'user_created']
vectorizeable = ['description', 'email_domain', 'name', 'org_desc', 'org_name', 'venue_name']
scalable = ['channels', 'body_length', 'gts', 'name_length', 'num_order', 'num_payouts', 'org_facebook', 'org_twitter', 'sale_duration', 'sale_duration2', 'user_age']
get_dummies_cols = ['country', 'currency', 'delivery_method', 'payout_type', 'previous_payouts', 'user_type', 'venue_country']